// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo;

#nullable disable

namespace Entidades.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("nombre_cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasDiscriminator<string>("Tipo").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entidades.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("id_venta")
                        .HasColumnType("int");

                    b.Property<decimal>("precio_unitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productoId")
                        .HasColumnType("int");

                    b.Property<decimal>("subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ventaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productoId");

                    b.HasIndex("ventaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("Entidades.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("id_sucursal")
                        .HasColumnType("int");

                    b.Property<int>("productoId")
                        .HasColumnType("int");

                    b.Property<int>("sucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productoId");

                    b.HasIndex("sucursalId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("Entidades.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("MetodosPago");

                    b.HasDiscriminator<string>("Tipo").HasValue("MetodoPago");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nombre_sucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Entidades.Mayorista", b =>
                {
                    b.HasBaseType("Entidades.Cliente");

                    b.Property<int>("cuit")
                        .HasColumnType("int");

                    b.Property<decimal>("descuento")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasDiscriminator().HasValue("Mayorista");
                });

            modelBuilder.Entity("Entidades.Minorista", b =>
                {
                    b.HasBaseType("Entidades.Cliente");

                    b.Property<int>("cuil")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Minorista");
                });

            modelBuilder.Entity("Entidades.Efectivo", b =>
                {
                    b.HasBaseType("Entidades.MetodoPago");

                    b.Property<decimal>("descuento_efectivo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasDiscriminator().HasValue("Efectivo");
                });

            modelBuilder.Entity("Entidades.Tarjeta", b =>
                {
                    b.HasBaseType("Entidades.MetodoPago");

                    b.Property<int>("cuotas")
                        .HasColumnType("int");

                    b.Property<decimal>("interes")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasDiscriminator().HasValue("Tarjeta");
                });

            modelBuilder.Entity("Entidades.Transferencia", b =>
                {
                    b.HasBaseType("Entidades.MetodoPago");

                    b.Property<decimal>("descuento_transferencia")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasDiscriminator().HasValue("Transferencia");
                });

            modelBuilder.Entity("Entidades.DetalleVenta", b =>
                {
                    b.HasOne("Entidades.Producto", "producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Venta", "venta")
                        .WithMany("detalleVenta")
                        .HasForeignKey("ventaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producto");

                    b.Navigation("venta");
                });

            modelBuilder.Entity("Entidades.Inventario", b =>
                {
                    b.HasOne("Entidades.Producto", "producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sucursal", "sucursal")
                        .WithMany("inventario_local")
                        .HasForeignKey("sucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producto");

                    b.Navigation("sucursal");
                });

            modelBuilder.Entity("Factura", b =>
                {
                    b.HasOne("Entidades.MetodoPago", "metodoPago")
                        .WithMany("Facturas")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Venta", "venta")
                        .WithOne("factura")
                        .HasForeignKey("Factura", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("metodoPago");

                    b.Navigation("venta");
                });

            modelBuilder.Entity("Venta", b =>
                {
                    b.HasOne("Entidades.Cliente", "cliente")
                        .WithMany("ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sucursal", "sucursal")
                        .WithMany("ventas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("sucursal");
                });

            modelBuilder.Entity("Entidades.Cliente", b =>
                {
                    b.Navigation("ventas");
                });

            modelBuilder.Entity("Entidades.MetodoPago", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Entidades.Producto", b =>
                {
                    b.Navigation("DetallesVenta");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Sucursal", b =>
                {
                    b.Navigation("inventario_local");

                    b.Navigation("ventas");
                });

            modelBuilder.Entity("Venta", b =>
                {
                    b.Navigation("detalleVenta");

                    b.Navigation("factura")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
